### ISSUE TITLE
app.steemconnect.com wants login again when switching in Desktop site in Google Chrome

### ISSUE THREAD

**Issue by kr-nahid** [samvanemelen/Debato#18] opened 2019-06-08 09:19 UTC
#### Expected behavior
it should not be going to app.steemconnect.com page for login when switching in Desktop site . 

#### Actual behavior
https://debato.org/ home page to going to app.steemconnect.com page when switching in Desktop site.

#### How to reproduce
1. go to https://debato.org/ with Google Chrome.
2. then login with steem connect
3. when login complete then  switching in Desktop site .
4. and note the bug

* Browser/App version: Google Chrome v75.0.3770.67
* Operating system: v8.1.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=DI3fg2Kyp9c

**Comment by samvanemelen** [comment] 2019-06-21 20:19
That is indeed a undesirable behavior. Thanks for discovering it! I could not reproduce it when switching between mobile/desktop view on a computer, but a mobile device indeed demonstrates the issue. it seems as if switching to the desktop view also induces a command to go to the previous page. It should be fixed now. Let me know if you continue to get the bug nevertheless.

**Closed by samvanemelen** 2019-06-21 20:19 UTC
